name: 'Power_BI_Service_Upload'
description: 'Deploys PBIX and RDL Files under 1 GB to the Power BI Service'
author: 'SkyHighGrowth'
branding:
  icon: 'upload'  
  color: 'yellow'
inputs:
  files:
    description: 'Files to deploy'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
      - ${{ inputs.files }}
